### PR TITLE
Admin menu bar: move 'Users' above 'Organizations' #629

### PR DESCRIPTION
**Pull request by juan-rivera-2020**
Here's the fix for admin menu bar list item re-ordering.  Please test.

### CODE REVIEW

**Comment by bluenevus** [comment]
There are conflicts in your code
https://github.com/MicroHealthLLC/mGis/pull/640/conflicts

[cid:image001.png@01D6A887.5E2B84D0]


Frank Tucker
Chief Executive Officer, Executive Office
t: 855-294-3547
m: 571-327-1211
frank.tucker@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by bluenevus** [comment]
you might have made the change on the older baseline.  lots of updates.  I would say make a new pull, validate your updates there, push then request the pull

**Comment by juan-rivera-2020** [comment]
Okay.  I’m looking into the conflicts now.  I always do a pull request before pushing, but I’ll look into it further and resolve asap.



Juan Rivera
Developer
t: 855-294-3547
m: 508-596-3665
juan.rivera@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by juan-rivera-2020** [comment]
The conflict may be in Line 1 of both files I pushed up.

LINE 1:  “<<<<<<< JR-10-16-20”

That’s not in the code I pushed up, but I’ll do another pull to validate the updates.


Juan Rivera
Developer
t: 855-294-3547
m: 508-596-3665
juan.rivera@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by juan-rivera-2020** [comment]
Please disregard this pull request.  Conflicts have been resolved, and another pull request was made.

**Pull request closed without merging**
