### PR TITLE
Created actions bar affixed to top of Task and Issue form in Facility Manager page.

### PR DESCRIPTION
**Pull request by juan-rivera-2020**
Result:
image

### CODE REVIEW

**Comment by bluenevus** [comment]
its affixed but not to the top you can see it scroll through

image

**Comment by JuanCodeAtATime** [comment]
It may be a cross-browser compatibility issue.  Or maybe it needs to be moved up a bit more?  On my screen, even moving it up 1% would move it above the div it’s contained in.  We can also stick it or affix it to the bottom of the form if that’s better for the flow.

**Comment by bluenevus** [comment]
I'm in chrome.  I think its the aspect ratio.  I'm on a 4:3 pixelbook running 1714 x 1143

**Comment by bluenevus** [comment]
but it doesn't matter if I change my screen resolution its still relative because I4:3 possibly?

**Comment by bluenevus** [comment]
definitely aspect ratio.  resize your screen and make it shorter and it will go over the border 
image

**Comment by juan-rivera-2020** [comment]
Yes...maybe not a cross-browser issue...I’m also in chrome.  I’ll tweak it.  But yeah, an alternative could be moving the bar to the bottom as filling out a form has a downward flow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

Juan Rivera
Developer
t: 855-294-3547
m: 508-596-3665
juan.rivera@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by juan-rivera-2020** [comment]
Okay...Yes.   I saw it go over the border a few times when I had my cell dev tools open.   I’ll make the adjustments 👍🏽

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

Juan Rivera
Developer
t: 855-294-3547
m: 508-596-3665
juan.rivera@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by bluenevus** [comment]
its also missing the rest of the buttons in the map view 
image

**Comment by bluenevus** [comment]
and the save button doesn't work in map view.  the back link wouldn't be needed if all the buttons were there and working.  Of course, it suffers the same placement issue as you see in the image above

**Pull request merged**
